/*

 DIALOGMAPCEMETERYT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 111

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __dialogmapcemeteryt_h_INCLUDE
#define __dialogmapcemeteryt_h_INCLUDE

/* Bank of tiles. */
#define dialogmapcemeterytBank 0

/* Super Gameboy palette 0 */
#define dialogmapcemeterytSGBPal0c0 0
#define dialogmapcemeterytSGBPal0c1 0
#define dialogmapcemeterytSGBPal0c2 0
#define dialogmapcemeterytSGBPal0c3 0

/* Super Gameboy palette 1 */
#define dialogmapcemeterytSGBPal1c0 6076
#define dialogmapcemeterytSGBPal1c1 8935
#define dialogmapcemeterytSGBPal1c2 6596
#define dialogmapcemeterytSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define dialogmapcemeterytSGBPal2c0 6076
#define dialogmapcemeterytSGBPal2c1 8935
#define dialogmapcemeterytSGBPal2c2 6596
#define dialogmapcemeterytSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define dialogmapcemeterytSGBPal3c0 6076
#define dialogmapcemeterytSGBPal3c1 8935
#define dialogmapcemeterytSGBPal3c2 6596
#define dialogmapcemeterytSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define dialogmapcemeterytCGBPal0c0 17240
#define dialogmapcemeterytCGBPal0c1 11057
#define dialogmapcemeterytCGBPal0c2 5509
#define dialogmapcemeterytCGBPal0c3 1250

/* Gameboy Color palette 1 */
#define dialogmapcemeterytCGBPal1c0 6076
#define dialogmapcemeterytCGBPal1c1 8935
#define dialogmapcemeterytCGBPal1c2 6596
#define dialogmapcemeterytCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define dialogmapcemeterytCGBPal2c0 6076
#define dialogmapcemeterytCGBPal2c1 8935
#define dialogmapcemeterytCGBPal2c2 6596
#define dialogmapcemeterytCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define dialogmapcemeterytCGBPal3c0 6076
#define dialogmapcemeterytCGBPal3c1 8935
#define dialogmapcemeterytCGBPal3c2 6596
#define dialogmapcemeterytCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define dialogmapcemeterytCGBPal4c0 6076
#define dialogmapcemeterytCGBPal4c1 8935
#define dialogmapcemeterytCGBPal4c2 6596
#define dialogmapcemeterytCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define dialogmapcemeterytCGBPal5c0 6076
#define dialogmapcemeterytCGBPal5c1 8935
#define dialogmapcemeterytCGBPal5c2 6596
#define dialogmapcemeterytCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define dialogmapcemeterytCGBPal6c0 6076
#define dialogmapcemeterytCGBPal6c1 8935
#define dialogmapcemeterytCGBPal6c2 6596
#define dialogmapcemeterytCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define dialogmapcemeterytCGBPal7c0 6076
#define dialogmapcemeterytCGBPal7c1 8935
#define dialogmapcemeterytCGBPal7c2 6596
#define dialogmapcemeterytCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char dialogmapcemeteryt[];

#endif

/* End of DIALOGMAPCEMETERYT.H */
