/*

 DIALOGTILES00.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 101

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __dialogtiles00_h_INCLUDE
#define __dialogtiles00_h_INCLUDE

/* Bank of tiles. */
#define dialogtiles00Bank 0

/* Super Gameboy palette 0 */
#define dialogtiles00SGBPal0c0 0
#define dialogtiles00SGBPal0c1 0
#define dialogtiles00SGBPal0c2 0
#define dialogtiles00SGBPal0c3 0

/* Super Gameboy palette 1 */
#define dialogtiles00SGBPal1c0 6076
#define dialogtiles00SGBPal1c1 8935
#define dialogtiles00SGBPal1c2 6596
#define dialogtiles00SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define dialogtiles00SGBPal2c0 6076
#define dialogtiles00SGBPal2c1 8935
#define dialogtiles00SGBPal2c2 6596
#define dialogtiles00SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define dialogtiles00SGBPal3c0 6076
#define dialogtiles00SGBPal3c1 8935
#define dialogtiles00SGBPal3c2 6596
#define dialogtiles00SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define dialogtiles00CGBPal0c0 32767
#define dialogtiles00CGBPal0c1 27482
#define dialogtiles00CGBPal0c2 8935
#define dialogtiles00CGBPal0c3 0

/* Gameboy Color palette 1 */
#define dialogtiles00CGBPal1c0 6076
#define dialogtiles00CGBPal1c1 8935
#define dialogtiles00CGBPal1c2 6596
#define dialogtiles00CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define dialogtiles00CGBPal2c0 6076
#define dialogtiles00CGBPal2c1 8935
#define dialogtiles00CGBPal2c2 6596
#define dialogtiles00CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define dialogtiles00CGBPal3c0 6076
#define dialogtiles00CGBPal3c1 8935
#define dialogtiles00CGBPal3c2 6596
#define dialogtiles00CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define dialogtiles00CGBPal4c0 6076
#define dialogtiles00CGBPal4c1 8935
#define dialogtiles00CGBPal4c2 6596
#define dialogtiles00CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define dialogtiles00CGBPal5c0 6076
#define dialogtiles00CGBPal5c1 8935
#define dialogtiles00CGBPal5c2 6596
#define dialogtiles00CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define dialogtiles00CGBPal6c0 6076
#define dialogtiles00CGBPal6c1 8935
#define dialogtiles00CGBPal6c2 6596
#define dialogtiles00CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define dialogtiles00CGBPal7c0 6076
#define dialogtiles00CGBPal7c1 8935
#define dialogtiles00CGBPal7c2 6596
#define dialogtiles00CGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char dialogtiles00[];

#endif

/* End of DIALOGTILES00.H */
