/*

 DMAPMINOTAURT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 111

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __dmapminotaurt_h_INCLUDE
#define __dmapminotaurt_h_INCLUDE

/* Bank of tiles. */
#define dmapminotaurtBank 0

/* Super Gameboy palette 0 */
#define dmapminotaurtSGBPal0c0 0
#define dmapminotaurtSGBPal0c1 0
#define dmapminotaurtSGBPal0c2 0
#define dmapminotaurtSGBPal0c3 0

/* Super Gameboy palette 1 */
#define dmapminotaurtSGBPal1c0 6076
#define dmapminotaurtSGBPal1c1 8935
#define dmapminotaurtSGBPal1c2 6596
#define dmapminotaurtSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define dmapminotaurtSGBPal2c0 6076
#define dmapminotaurtSGBPal2c1 8935
#define dmapminotaurtSGBPal2c2 6596
#define dmapminotaurtSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define dmapminotaurtSGBPal3c0 6076
#define dmapminotaurtSGBPal3c1 8935
#define dmapminotaurtSGBPal3c2 6596
#define dmapminotaurtSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define dmapminotaurtCGBPal0c0 32767
#define dmapminotaurtCGBPal0c1 9951
#define dmapminotaurtCGBPal0c2 27104
#define dmapminotaurtCGBPal0c3 0

/* Gameboy Color palette 1 */
#define dmapminotaurtCGBPal1c0 6076
#define dmapminotaurtCGBPal1c1 8935
#define dmapminotaurtCGBPal1c2 6596
#define dmapminotaurtCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define dmapminotaurtCGBPal2c0 6076
#define dmapminotaurtCGBPal2c1 8935
#define dmapminotaurtCGBPal2c2 6596
#define dmapminotaurtCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define dmapminotaurtCGBPal3c0 6076
#define dmapminotaurtCGBPal3c1 8935
#define dmapminotaurtCGBPal3c2 6596
#define dmapminotaurtCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define dmapminotaurtCGBPal4c0 6076
#define dmapminotaurtCGBPal4c1 8935
#define dmapminotaurtCGBPal4c2 6596
#define dmapminotaurtCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define dmapminotaurtCGBPal5c0 6076
#define dmapminotaurtCGBPal5c1 8935
#define dmapminotaurtCGBPal5c2 6596
#define dmapminotaurtCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define dmapminotaurtCGBPal6c0 6076
#define dmapminotaurtCGBPal6c1 8935
#define dmapminotaurtCGBPal6c2 6596
#define dmapminotaurtCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define dmapminotaurtCGBPal7c0 6076
#define dmapminotaurtCGBPal7c1 8935
#define dmapminotaurtCGBPal7c2 6596
#define dmapminotaurtCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char dmapminotaurt[];

#endif

/* End of DMAPMINOTAURT.H */
