/*

 DMAPMINET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 101

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __dmapminet_h_INCLUDE
#define __dmapminet_h_INCLUDE

/* Bank of tiles. */
#define dmapminetBank 0

/* Super Gameboy palette 0 */
#define dmapminetSGBPal0c0 0
#define dmapminetSGBPal0c1 0
#define dmapminetSGBPal0c2 0
#define dmapminetSGBPal0c3 0

/* Super Gameboy palette 1 */
#define dmapminetSGBPal1c0 6076
#define dmapminetSGBPal1c1 8935
#define dmapminetSGBPal1c2 6596
#define dmapminetSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define dmapminetSGBPal2c0 6076
#define dmapminetSGBPal2c1 8935
#define dmapminetSGBPal2c2 6596
#define dmapminetSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define dmapminetSGBPal3c0 6076
#define dmapminetSGBPal3c1 8935
#define dmapminetSGBPal3c2 6596
#define dmapminetSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define dmapminetCGBPal0c0 32767
#define dmapminetCGBPal0c1 21438
#define dmapminetCGBPal0c2 797
#define dmapminetCGBPal0c3 0

/* Gameboy Color palette 1 */
#define dmapminetCGBPal1c0 6076
#define dmapminetCGBPal1c1 8935
#define dmapminetCGBPal1c2 6596
#define dmapminetCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define dmapminetCGBPal2c0 6076
#define dmapminetCGBPal2c1 8935
#define dmapminetCGBPal2c2 6596
#define dmapminetCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define dmapminetCGBPal3c0 6076
#define dmapminetCGBPal3c1 8935
#define dmapminetCGBPal3c2 6596
#define dmapminetCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define dmapminetCGBPal4c0 6076
#define dmapminetCGBPal4c1 8935
#define dmapminetCGBPal4c2 6596
#define dmapminetCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define dmapminetCGBPal5c0 6076
#define dmapminetCGBPal5c1 8935
#define dmapminetCGBPal5c2 6596
#define dmapminetCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define dmapminetCGBPal6c0 6076
#define dmapminetCGBPal6c1 8935
#define dmapminetCGBPal6c2 6596
#define dmapminetCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define dmapminetCGBPal7c0 6076
#define dmapminetCGBPal7c1 8935
#define dmapminetCGBPal7c2 6596
#define dmapminetCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char dmapminet[];

#endif

/* End of DMAPMINET.H */
