/*

 DMAPINTROT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 111

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __dmapintrot_h_INCLUDE
#define __dmapintrot_h_INCLUDE

/* Bank of tiles. */
#define dmapintrotBank 0

/* Super Gameboy palette 0 */
#define dmapintrotSGBPal0c0 0
#define dmapintrotSGBPal0c1 0
#define dmapintrotSGBPal0c2 0
#define dmapintrotSGBPal0c3 0

/* Super Gameboy palette 1 */
#define dmapintrotSGBPal1c0 6076
#define dmapintrotSGBPal1c1 8935
#define dmapintrotSGBPal1c2 6596
#define dmapintrotSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define dmapintrotSGBPal2c0 6076
#define dmapintrotSGBPal2c1 8935
#define dmapintrotSGBPal2c2 6596
#define dmapintrotSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define dmapintrotSGBPal3c0 6076
#define dmapintrotSGBPal3c1 8935
#define dmapintrotSGBPal3c2 6596
#define dmapintrotSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define dmapintrotCGBPal0c0 4063
#define dmapintrotCGBPal0c1 4063
#define dmapintrotCGBPal0c2 10570
#define dmapintrotCGBPal0c3 0

/* Gameboy Color palette 1 */
#define dmapintrotCGBPal1c0 6076
#define dmapintrotCGBPal1c1 8935
#define dmapintrotCGBPal1c2 6596
#define dmapintrotCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define dmapintrotCGBPal2c0 6076
#define dmapintrotCGBPal2c1 8935
#define dmapintrotCGBPal2c2 6596
#define dmapintrotCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define dmapintrotCGBPal3c0 6076
#define dmapintrotCGBPal3c1 8935
#define dmapintrotCGBPal3c2 6596
#define dmapintrotCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define dmapintrotCGBPal4c0 6076
#define dmapintrotCGBPal4c1 8935
#define dmapintrotCGBPal4c2 6596
#define dmapintrotCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define dmapintrotCGBPal5c0 6076
#define dmapintrotCGBPal5c1 8935
#define dmapintrotCGBPal5c2 6596
#define dmapintrotCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define dmapintrotCGBPal6c0 6076
#define dmapintrotCGBPal6c1 8935
#define dmapintrotCGBPal6c2 6596
#define dmapintrotCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define dmapintrotCGBPal7c0 6076
#define dmapintrotCGBPal7c1 8935
#define dmapintrotCGBPal7c2 6596
#define dmapintrotCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char dmapintrot[];

#endif

/* End of DMAPINTROT.H */
