/*

 IDMAPTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 31

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __idmaptiles_h_INCLUDE
#define __idmaptiles_h_INCLUDE

/* Bank of tiles. */
#define idmaptilesBank 0

/* Super Gameboy palette 0 */
#define idmaptilesSGBPal0c0 0
#define idmaptilesSGBPal0c1 0
#define idmaptilesSGBPal0c2 0
#define idmaptilesSGBPal0c3 0

/* Super Gameboy palette 1 */
#define idmaptilesSGBPal1c0 6076
#define idmaptilesSGBPal1c1 8935
#define idmaptilesSGBPal1c2 6596
#define idmaptilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define idmaptilesSGBPal2c0 6076
#define idmaptilesSGBPal2c1 8935
#define idmaptilesSGBPal2c2 6596
#define idmaptilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define idmaptilesSGBPal3c0 6076
#define idmaptilesSGBPal3c1 8935
#define idmaptilesSGBPal3c2 6596
#define idmaptilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define idmaptilesCGBPal0c0 17240
#define idmaptilesCGBPal0c1 11057
#define idmaptilesCGBPal0c2 5509
#define idmaptilesCGBPal0c3 1250

/* Gameboy Color palette 1 */
#define idmaptilesCGBPal1c0 6076
#define idmaptilesCGBPal1c1 8935
#define idmaptilesCGBPal1c2 6596
#define idmaptilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define idmaptilesCGBPal2c0 6076
#define idmaptilesCGBPal2c1 8935
#define idmaptilesCGBPal2c2 6596
#define idmaptilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define idmaptilesCGBPal3c0 6076
#define idmaptilesCGBPal3c1 8935
#define idmaptilesCGBPal3c2 6596
#define idmaptilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define idmaptilesCGBPal4c0 6076
#define idmaptilesCGBPal4c1 8935
#define idmaptilesCGBPal4c2 6596
#define idmaptilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define idmaptilesCGBPal5c0 6076
#define idmaptilesCGBPal5c1 8935
#define idmaptilesCGBPal5c2 6596
#define idmaptilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define idmaptilesCGBPal6c0 6076
#define idmaptilesCGBPal6c1 8935
#define idmaptilesCGBPal6c2 6596
#define idmaptilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define idmaptilesCGBPal7c0 6076
#define idmaptilesCGBPal7c1 8935
#define idmaptilesCGBPal7c2 6596
#define idmaptilesCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char idmaptiles[];

#endif

/* End of IDMAPTILES.H */
