/*

 IDSCORPIONTAILTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 31

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __idscorpiontailtiles_h_INCLUDE
#define __idscorpiontailtiles_h_INCLUDE

/* Bank of tiles. */
#define idscorpiontailtilesBank 0

/* Super Gameboy palette 0 */
#define idscorpiontailtilesSGBPal0c0 0
#define idscorpiontailtilesSGBPal0c1 0
#define idscorpiontailtilesSGBPal0c2 0
#define idscorpiontailtilesSGBPal0c3 0

/* Super Gameboy palette 1 */
#define idscorpiontailtilesSGBPal1c0 6076
#define idscorpiontailtilesSGBPal1c1 8935
#define idscorpiontailtilesSGBPal1c2 6596
#define idscorpiontailtilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define idscorpiontailtilesSGBPal2c0 6076
#define idscorpiontailtilesSGBPal2c1 8935
#define idscorpiontailtilesSGBPal2c2 6596
#define idscorpiontailtilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define idscorpiontailtilesSGBPal3c0 6076
#define idscorpiontailtilesSGBPal3c1 8935
#define idscorpiontailtilesSGBPal3c2 6596
#define idscorpiontailtilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define idscorpiontailtilesCGBPal0c0 17240
#define idscorpiontailtilesCGBPal0c1 11057
#define idscorpiontailtilesCGBPal0c2 5509
#define idscorpiontailtilesCGBPal0c3 1250

/* Gameboy Color palette 1 */
#define idscorpiontailtilesCGBPal1c0 6076
#define idscorpiontailtilesCGBPal1c1 8935
#define idscorpiontailtilesCGBPal1c2 6596
#define idscorpiontailtilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define idscorpiontailtilesCGBPal2c0 6076
#define idscorpiontailtilesCGBPal2c1 8935
#define idscorpiontailtilesCGBPal2c2 6596
#define idscorpiontailtilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define idscorpiontailtilesCGBPal3c0 6076
#define idscorpiontailtilesCGBPal3c1 8935
#define idscorpiontailtilesCGBPal3c2 6596
#define idscorpiontailtilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define idscorpiontailtilesCGBPal4c0 6076
#define idscorpiontailtilesCGBPal4c1 8935
#define idscorpiontailtilesCGBPal4c2 6596
#define idscorpiontailtilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define idscorpiontailtilesCGBPal5c0 6076
#define idscorpiontailtilesCGBPal5c1 8935
#define idscorpiontailtilesCGBPal5c2 6596
#define idscorpiontailtilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define idscorpiontailtilesCGBPal6c0 6076
#define idscorpiontailtilesCGBPal6c1 8935
#define idscorpiontailtilesCGBPal6c2 6596
#define idscorpiontailtilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define idscorpiontailtilesCGBPal7c0 6076
#define idscorpiontailtilesCGBPal7c1 8935
#define idscorpiontailtilesCGBPal7c2 6596
#define idscorpiontailtilesCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char idscorpiontailtiles[];

#endif

/* End of IDSCORPIONTAILTILES.H */
