/*

 TITLESCREENTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 210

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __titlescreentiles_h_INCLUDE
#define __titlescreentiles_h_INCLUDE

/* Bank of tiles. */
#define titlescreentilesBank 0

/* Super Gameboy palette 0 */
#define titlescreentilesSGBPal0c0 0
#define titlescreentilesSGBPal0c1 0
#define titlescreentilesSGBPal0c2 0
#define titlescreentilesSGBPal0c3 0

/* Super Gameboy palette 1 */
#define titlescreentilesSGBPal1c0 6076
#define titlescreentilesSGBPal1c1 8935
#define titlescreentilesSGBPal1c2 6596
#define titlescreentilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define titlescreentilesSGBPal2c0 6076
#define titlescreentilesSGBPal2c1 8935
#define titlescreentilesSGBPal2c2 6596
#define titlescreentilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define titlescreentilesSGBPal3c0 6076
#define titlescreentilesSGBPal3c1 8935
#define titlescreentilesSGBPal3c2 6596
#define titlescreentilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define titlescreentilesCGBPal0c0 32767
#define titlescreentilesCGBPal0c1 8935
#define titlescreentilesCGBPal0c2 6596
#define titlescreentilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define titlescreentilesCGBPal1c0 32767
#define titlescreentilesCGBPal1c1 21140
#define titlescreentilesCGBPal1c2 12684
#define titlescreentilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define titlescreentilesCGBPal2c0 32767
#define titlescreentilesCGBPal2c1 21140
#define titlescreentilesCGBPal2c2 536
#define titlescreentilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define titlescreentilesCGBPal3c0 32767
#define titlescreentilesCGBPal3c1 2815
#define titlescreentilesCGBPal3c2 9752
#define titlescreentilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define titlescreentilesCGBPal4c0 32767
#define titlescreentilesCGBPal4c1 32660
#define titlescreentilesCGBPal4c2 22752
#define titlescreentilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define titlescreentilesCGBPal5c0 32767
#define titlescreentilesCGBPal5c1 8863
#define titlescreentilesCGBPal5c2 30
#define titlescreentilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define titlescreentilesCGBPal6c0 32767
#define titlescreentilesCGBPal6c1 32660
#define titlescreentilesCGBPal6c2 9752
#define titlescreentilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define titlescreentilesCGBPal7c0 32767
#define titlescreentilesCGBPal7c1 21140
#define titlescreentilesCGBPal7c2 16896
#define titlescreentilesCGBPal7c3 4332
/* Start of tile array. */
extern const unsigned char titlescreentiles[];

#endif

/* End of TITLESCREENTILES.H */
