typedef enum{
	EMPTY_STRING,
	MISSIONI_IN_CORSO,
	FIND_BLACKIE_TITLE,
	FIND_BLACKIE_D0,
	FIND_BLACKIE_D1,
	HELP_DESPARATE_WOMAN_TITLE
}DD_TO_BE_LOCALIZED;

void GetLocalizedDDLabel_EN(DD_TO_BE_LOCALIZED label, char* d) BANKED;