typedef enum{
	EMPTY_STRING,
	MISSIONI_IN_CORSO,
	MISSIONI_COMPLETATE,
	FIND_BLACKIE_TITLE,
	FIND_BLACKIE_D0,
	FIND_BLACKIE_D1,
	FIND_BLACKIE_D2,
	FIND_BLACKIE_D3,
	FIND_BLACKIE_D4,
	FIND_BLACKIE_D5,
	FIND_BLACKIE_D6,
	FIND_BLACKIE_D7,
	ENGAGE_SMITH_TITLE,
	ENGAGE_SMITH_D0,
	ENGAGE_SMITH_D1,
	HELP_DESPARATE_WIDOW_TITLE
}DD_TO_BE_LOCALIZED;

void GetLocalizedDDLabel_EN(DD_TO_BE_LOCALIZED label, char* d) BANKED;