#include <gb/gb.h>

void Anim_StudioLoading_0() BANKED;
void Anim_StudioLoading_1() BANKED;
void Anim_StudioLoading_2() BANKED;
void Anim_Crossbow_0() BANKED;
void Anim_Crossbow_1() BANKED;
void Anim_Ground_Straight_0() BANKED;
void Anim_Ground_Straight_1() BANKED;
void Inv_change_detail(UINT8 item, UINT8 isEmpty) BANKED;
void Anim_Titlescreen_0() BANKED;
void Anim_Titlescreen_1() BANKED;
void Anim_Titlescreen_2() BANKED;
void Anim_Titlescreen_3() BANKED;
void Anim_Ow_0() BANKED;
void Anim_Ow_1() BANKED;
void Anim_Ow_2() BANKED;
void Anim_Ow_3() BANKED;
void Anim_Ow_4() BANKED;
void Anim_Ow_5() BANKED;
void Anim_Ow_see_0() BANKED;
void Anim_Ow_see_1() BANKED;
void Anim_Ow_see_2() BANKED;
void Anim_Ow_see_3() BANKED;
void Anim_Cave_0() BANKED;
void Anim_Cave_1() BANKED;
void Anim_Cave_2() BANKED;
void Anim_Cave_3() BANKED;
void Anim_Cave_4() BANKED;
void Anim_Cave_5() BANKED;
void Anim_Cart_0() BANKED;
void Anim_Cart_1() BANKED;
void Anim_Cart_2() BANKED;
void Anim_Cart_3() BANKED;
void Anim_Cart_4() BANKED;
void Anim_Cart_5() BANKED;